Python Web/epfive/epfive/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('epfive.web.urls')),
]

Python Web/epfive/epfive/web/urls.py
from django.urls import path

from epfive.web.views import IndexView, RecipeCreateView, RecipeDetailsView, RecipeDeleteView, EditRecipeView

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('create/', RecipeCreateView.as_view(), name='create'),
    path('edit/<int:pk>/', EditRecipeView.as_view(), name='edit'),
    path('delete/<int:pk>/', RecipeDeleteView.as_view(), name='delete'),
    path('details/<int:pk>/', RecipeDetailsView.as_view(), name='details'),

]

Python Web/epfive/epfive/web/models.py
from django.db import models


# Create your models here.
class Recipe(models.Model):

    title = models.CharField(max_length=30, null=False, blank=False)

    image_URL = models.URLField(null=False, blank=False)

    description = models.TextField(null=False, blank=False)

    ingredients = models.CharField(max_length=250, null=False, blank=False)

    time = models.IntegerField(null=False, blank=False)

Python Web/epfive/epfive/web/forms.py
from django import forms

from epfive.web.models import Recipe


class BaseRecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = '__all__'


class CreateRecipeForm(BaseRecipeForm):
    pass


class EditRecipeForm(BaseRecipeForm):
    pass


class DeleteRecipeForm(BaseRecipeForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.__disable_field()

    def save(self, commit=True):
        if commit:
            self.instance.delete()
        return self.instance

    def __disable_field(self):
        for _, field in self.fields.items():
            field.widget.attrs['readonly'] = 'readonly'

Python Web/epfive/epfive/web/views.py
from django.shortcuts import render, redirect

from epfive.web.forms import CreateRecipeForm, EditRecipeForm, DeleteRecipeForm
from epfive.web.models import Recipe
from django.views import generic as views


class IndexView(views.View):
    def get(self, request):
        context = {
            'recipes': Recipe.objects.all()
        }
        return render(request, 'index.html', context)


class RecipeCreateView(views.CreateView):
    model = Recipe
    template_name = 'create.html'
    fields = '__all__'
    success_url = '/'


class RecipeDetailsView(views.DetailView):
    model = Recipe
    template_name = 'details.html'


class EditRecipeView(views.UpdateView):
    model = Recipe
    template_name = 'edit.html'
    fields = '__all__'
    success_url = '/'
# def edit(request, pk):
#     recipe = Recipe.objects.filter(pk=pk).get()
#     if request.method == 'GET':
#         form = EditRecipeForm(instance=recipe)
#     else:
#         form = EditRecipeForm(request.POST, instance=recipe)
#         if form.is_valid():
#             form.save()
#             return redirect('index')
#     context = {
#         'form': form,
#         'recipe': recipe,
#     }
#     return render(request, 'edit.html', context)


class RecipeDeleteView(views.DeleteView):
    model = Recipe
    template_name = 'delete.html'
    success_url = '/'

Python Web/epfive/templates/create.html
{% load static %}
<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Recipes</title>
</head>

<body>
     
 <nav>
    <ul>
        <img src="{% static 'images/chef.png' %}" alt="chef">
        <li class="title"><a href="{% url 'index' %}">Recipes</a></li>
        <li><a href="{% url 'create' %}">Add Recipe</a></li>
    </ul>
</nav>
    <div class="container">
        
<h1>Create Recipe</h1>
<div class="items-container">
    <div class="item">
        <form method="post" action="{% url 'create' %}">
            {{ form}}
{#            <label for="title">Title</label>#}
{#            <input type="text" name="title" maxlength="30" required="" id="id_title">#}
{#            <label for="imageURL">Image URL</label>#}
{#            <input type="url" name="image_url" maxlength="200" required="" id="id_image_url">#}
{#            <label for="description">Description</label>#}
{#            <textarea name="description" cols="40" rows="10" required="" id="id_description"></textarea>#}
{#            <label for="ingredients">Ingredients</label>#}
{#            <input type="text" name="ingredients" maxlength="250" required="" id="id_ingredients">#}
{#            <label for="time">Time (Minutes)</label>#}
{#            <input type="number" name="time" required="" id="id_time">#}
            <input type="submit" value="Create">
            {% csrf_token %}
        </form>
    </div>
</div>

    </div>


</body></html>

Python Web/epfive/templates/delete.html
{% load static %}
<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Recipes</title>
</head>

<body>
     
 <nav>
    <ul>
        <img src="{% static 'images/chef.png' %}" alt="chef">
        <li class="title"><a href="{% url 'index' %}">Recipes</a></li>
        <li><a href="{% url 'create' %}">Add Recipe</a></li>
    </ul>
</nav>
    <div class="container">
        
<h1>Delete Recipe</h1>
<div class="items-container">
    <div class="item">
        <form method="post" action='{% url 'delete' pk=recipe.pk %}'>
            {{ form }}
{#            <label for="title">Title</label>#}
{#            <input type="text" name="title" value="Homemade Chicken Soup" maxlength="30" disabled="" required="" id="id_title">#}
{#            <label for="imageURL">Image URL</label>#}
{#            <input type="url" name="image_url" value="https://i.ytimg.com/vi/o91gT73mQhg/maxresdefault.jpg" maxlength="200" disabled="" required="" id="id_image_url">#}
{#            <label for="description">Description</label>#}
{#            <textarea name="description" cols="40" rows="10" disabled="" required="" id="id_description">Put the chicken, carrots, celery and onion in a large soup pot and cover with cold water. Heat and simmer, uncovered, until the chicken meat falls off of the bones (skim off foam every so often).#}
{#Take everything out of the pot. Strain the broth. Pick the meat off of the bones and chop the carrots, celery and onion. Season the broth with salt, pepper and chicken bouillon to taste, if desired. Return the chicken, carrots, celery and onion to the pot, stir together, and serve.</textarea>#}
{#            <label for="ingredients">Ingredients</label>#}
{#            <input type="text" name="ingredients" value="1 (3 pound) whole chicken, 4 medium (blank)s carrots halved, 4 stalks celery halved, 1 large onion halved, water to cover, salt and pepper to taste, 1 teaspoon chicken bouillon granules" maxlength="250" disabled="" required="" id="id_ingredients">#}
{#            <label for="time">Time (Minutes)</label>#}
{#            <input type="number" name="time" value="30" disabled="" required="" id="id_time">#}
            <input type="submit" class="button delete" value="Delete">
            {% csrf_token %}
        </form>
    </div>
</div>

    </div>


</body></html>

Python Web/epfive/templates/details.html
{% load static %}
<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    <title>Recipes</title>
</head>

<body>

 <nav>
    <ul>
        <img src="{% static 'images/chef.png' %}" alt="chef">
        <li class="title"><a href="{% url 'index' %}">Recipes</a></li>
        <li><a href="{% url 'create' %}">Add Recipe</a></li>
    </ul>
</nav>
    <div class="container">

<h1>Recipe Details</h1>
        <div class="items-container">
            <div class="item">
                <h2>{{ recipe.title }}</h2>
                <img class="detail-img" src="{{ recipe.image_URL}}" alt="recipe-image">
                <div class="time">
                    <img src="{% static 'images/clock.png' %}">
                    <p>{{ recipe.time }}</p>
                </div>
                <h3>Ingredients</h3>
                <ul>
                    {% for ingridient in recipe.ingredients %}
                        <li>{{ ingridient}}</li>
                    {% endfor %}


                </ul>
                <h3>How to prepare?</h3>
                <div class="recipe-info-full">
                    {{ recipe.description }}

                </div>
                <div class="buttons-container">
                    <a class="button edit" href="{% url 'edit' pk=recipe.pk %}">Edit</a>
                    <a class="button delete" href="{% url 'delete' pk=recipe.pk %}">Delete</a>
                </div>
            </div>
        </div>

    </div>


</body></html>

Python Web/epfive/templates/edit.html
{% load static %}
<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Recipes</title>
</head>

<body>
     
 <nav>
    <ul>
        <img src="{% static 'images/chef.png' %}" alt="chef">
        <li class="title"><a href="{% url 'index' %}">Recipes</a></li>
        <li><a href="{% url 'create' %}">Add Recipe</a></li>
    </ul>
</nav>
    <div class="container">
        
<h1>Edit Recipe</h1>
<div class="items-container">
    <div class="item">
        <form method="post" action={% url 'edit' pk=recipe.pk%}>
            {{ form }}
{#            <label for="title">Title</label>#}
{#            <input type="text" name="title" value="Homemade Chicken Soup" maxlength="30" required="" id="id_title">#}
{#            <label for="imageURL">Image URL</label>#}
{#            <input type="url" name="image_url" value="https://i.ytimg.com/vi/o91gT73mQhg/maxresdefault.jpg" maxlength="200"  required="" id="id_image_url">#}
{#            <label for="description">Description</label>#}
{#            <textarea name="description" cols="40" rows="10"  required="" id="id_description">Put the chicken, carrots, celery and onion in a large soup pot and cover with cold water. Heat and simmer, uncovered, until the chicken meat falls off of the bones (skim off foam every so often).#}
{#Take everything out of the pot. Strain the broth. Pick the meat off of the bones and chop the carrots, celery and onion. Season the broth with salt, pepper and chicken bouillon to taste, if desired. Return the chicken, carrots, celery and onion to the pot, stir together, and serve.</textarea>#}
{#            <label for="ingredients">Ingredients</label>#}
{#            <input type="text" name="ingredients" value="1 (3 pound) whole chicken, 4 medium (blank)s carrots halved, 4 stalks celery halved, 1 large onion halved, water to cover, salt and pepper to taste, 1 teaspoon chicken bouillon granules" maxlength="250"  required="" id="id_ingredients">#}
{#            <label for="time">Time (Minutes)</label>#}
{#            <input type="number" name="time" value="30" required="" id="id_time">#}
            <input type="submit" class="button edit" value="Edit">
            {% csrf_token %}
        </form>
    </div>
</div>

    </div>


</body></html>

Python Web/epfive/templates/index.html
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Recipes</title>
</head>

<body>

<nav>
    <ul>
        <img src="{% static 'images/chef.png' %}" alt="chef">
        <li class="title"><a href="{% url 'index' %}">Recipes</a></li>
        <li><a href="{% url 'create' %}">Add Recipe</a></li>
    </ul>
</nav>
<div class="container">


    {% if recipes %}
        <h1>My Recipes</h1>
        {% for recipe in recipes %}
            <div class="items-container">
                <div class="item">
                    <h2>{{ recipe.title }}</h2>
                    <img class="detail-img" src="{{ recipe.image_URL }}" alt="recipe-image">
                    <div class="recipe-info">
                        {{ recipe.description }}
                        {#                    Put the chicken, carrots, celery and onion in a large soup pot and cover with cold water. Heat and simmer, uncovered, until the chicken meat falls off of the bones (skim off foam every so often). Take everything out of the pot. Strain the broth. Pick#}
                        {#                    the meat off of the bones and chop the carrots, celery and onion. Season the broth with salt, pepper and chicken bouillon to taste, if desired. Return the chicken, carrots, celery and onion to the pot, stir together, and serve.#}
                    </div>
                    <div class="buttons-container">
                        <a class="button detail" href="{% url 'details' pk=recipe.pk %}">Details</a>
                        <a class="button edit" href="{% url 'edit' pk=recipe.pk %}">Edit</a>
                        <a class="button delete" href="{% url 'delete' pk=recipe.pk %}">Delete</a>
                    </div>
                </div>

                {#            <div class="item">#}
                {#                <h2>Cardamom Maple Salmon (Edit)</h2>#}
                {#                <img class="detail-img" src="https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F1122494.jpg&amp;w=596&amp;h=596&amp;c=sc&amp;poi=face&amp;q=85" alt="recipe-image">#}
                {#                <div class="recipe-info">#}
                {#                    Stir salt, paprika, cardamom, coriander, and black pepper together in a bowl. Add oil and maple syrup and stir until evenly combined. Preheat a non-stick frying pan over medium-high heat, about 350 degrees F (175 degrees C). Dredge salmon pieces through#}
                {#                    the maple syrup mixture until evenly coated on all sides. Cook salmon in the preheated pan until fish flakes easily with a fork, 5 to 7 minutes per side.#}
                {#                </div>#}
                {#                <div class="buttons-container">#}
                {#                    <a class="button detail" href="./details.html">Details</a>#}
                {#                    <a class="button edit" href="./edit.html">Edit</a>#}
                {#                    <a class="button delete" href="./delete.html">Delete</a>#}
                {#                </div>#}
            </div>
        {% endfor %}
    {% else %}
        <h2>There are no recipes.</h2>
    {% endif %}

</div>

</div>


</body>

</html>