Python Web/epfour/epfour/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('epfour.web.urls')),
]

Python Web/epfour/epfour/web/urls.py
from django.urls import path

from epfour.web.views import index, add_note, edit_note, delete_note, details_note, profile, create_profile

urlpatterns = [
    path('', index, name='index'),
    path('add/', add_note, name='add note'),
    path('edit/<int:pk>/', edit_note, name='edit note'),
    path('delete/<int:pk>/', delete_note, name='delete note'),
    path('details/<int:pk>/', details_note, name='details note'),
    path('profile/', profile, name='profile'),
    path('profile/create/', create_profile, name='create profile'),
]

Python Web/epfour/epfour/web/models.py
from django.db import models


# Create your models here.


class Profile(models.Model):
    MAX_LENGTH_NAME = 20

    first_name = models.CharField(null=False, blank=False, max_length=MAX_LENGTH_NAME)

    last_name = models.CharField(null=False, blank=False, max_length=MAX_LENGTH_NAME)

    age = models.IntegerField(null=False, blank=False)

    image_URL = models.URLField(null=False, blank=False)


class Note(models.Model):
    MAX_LENGTH_TITLE = 30

    title = models.CharField(null=False, blank=False, max_length=MAX_LENGTH_TITLE)

    image_URL = models.URLField(null=False, blank=False)

    content = models.TextField(null=False, blank=False)

Python Web/epfour/epfour/web/forms.py
from django import forms

from epfour.web.models import Profile, Note


class BaseProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = '__all__'


class ProfileCreateForm(BaseProfileForm):
    pass


class ProfileDeleteForm(BaseProfileForm):
    def save(self, commit=True):
        if commit:
            self.instance.delete()
            Note.objects.all().delete()
        return self.instance


class BaseNoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = '__all__'


class NoteCreateForm(BaseNoteForm):
    pass


class EditNoteForm(BaseNoteForm):
    pass


class DeleteNoteForm(BaseNoteForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.__disable_fields()

    def save(self, commit=True):
        if commit:
            self.instance.delete()
        return self.instance

    def __disable_fields(self):
        for _, field in self.fields.items():
            field.widget.attrs['readonly'] = 'readonly'

Python Web/epfour/epfour/web/views.py
from django.shortcuts import render, redirect

from epfour.web.forms import ProfileCreateForm, NoteCreateForm, EditNoteForm, DeleteNoteForm, ProfileDeleteForm
from epfour.web.models import Profile, Note


def get_profile():
    try:
        return Profile.objects.get()
    except:
        return None


def index(request):
    profile = get_profile()
    if profile is None:
        return redirect('create profile')
    context = {
        'notes': Note.objects.all()
    }
    return render(request, 'home-with-profile.html', context)


def add_note(request):
    if request.method == 'GET':
        form = NoteCreateForm()
    else:
        form = NoteCreateForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('index')
    context = {
        'form': form,
    }
    return render(request, 'note-create.html', context)


def edit_note(request, pk):
    note = Note.objects.filter(pk=pk).get()
    if request.method == 'GET':
        form = EditNoteForm(instance=note)
    else:
        form = EditNoteForm(request.POST, instance=note)
        if form.is_valid():
            form.save()
            return redirect('index')
    context = {
        'form': form,
        'note': note,
    }
    return render(request, 'note-edit.html', context)


def delete_note(request, pk):
    note = Note.objects.filter(pk=pk).get()
    if request.method == 'GET':
        form = DeleteNoteForm(instance=note)
    else:
        form = DeleteNoteForm(request.POST, instance=note)
        if form.is_valid():
            form.save()
            return redirect('index')
    context = {
        'form': form,
        'note': note,
    }
    return render(request, 'note-delete.html', context)


def details_note(request, pk):
    note = Note.objects.filter(pk=pk).get()
    context = {
        'note': note,
    }
    return render(request, 'note-details.html', context)


def profile(request):
    profile = get_profile()
    notes = Note.objects.count()
    if request.method == 'GET':
        form = ProfileDeleteForm(instance=profile)
    else:
        form = ProfileDeleteForm(request.POST, instance=profile)
        if form.is_valid():
            form.save()

            return redirect('index')
    context = {
        'form': form,
        'profile': profile,
        'notes': notes,
    }
    return render(request, 'profile.html', context)


def create_profile(request):

    if request.method == 'GET':
        form = ProfileCreateForm()
    else:
        form = ProfileCreateForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('index')
    context = {
        'form': form,
    }
    return render(request, 'home-no-profile.html', context)

Python Web/epfour/templates/home-no-profile.html
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css'%}" />
        <title>Notes</title>
    </head>

    <body>
        <!--navigation bar-->
        <header>
            <nav>
                <ul>
                    <li class="img"><img src="{% static 'images/note.png' %}" width="32" height="32" /></li>

                    <li><a href="{% url 'index' %}">Notes</a></li>
                </ul>
            </nav>
        </header>
        <!--end navigation bar-->

        <div class="body">
            <!--headings-->
            <h1>Enter Your Data</h1>
            <!--end headings-->

            <!--profile data form-->
            <div class="form">
                <form method="post" action="{% url 'create profile' %}">
                    {{ form }}
{#                    <input type="hidden" name="csrfmiddlewaretoken" value="97MmAxmrs7yPXUamEdIgRY80OHEP383f6VukAC6agPNIW60LqTcnIQlM6YCYPjc0" />#}
{#                    <label for="firstName">First Name</label>#}
{#                    <input type="text" name="first_name" maxlength="15" required="" id="id_first_name" />#}
{##}
{#                    <label for="lastName">Last Name</label>#}
{#                    <input type="text" name="last_name" maxlength="15" required="" id="id_last_name" />#}
{##}
{#                    <label for="age">Age</label>#}
{#                    <input type="number" name="age" required="" id="id_age" />#}
{##}
{#                    <label for="profilePhoto">Link to Profile Image</label>#}
{#                    <input type="url" name="profile_image" required="" id="id_image" />#}

                    <input type="submit" value="SUBMIT" />
                    {% csrf_token %}
                </form>
            </div>
            <!--end profile data form-->
        </div>

        <footer>
            <div>Python Web Basics Exam @SoftUni</div>
        </footer>
    </body>
</html>

Python Web/epfour/templates/home-with-profile.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="stylesheet" type="text/css" href="/static/css/style.css"/>
    <title>Notes</title>
</head>

<body>
<!--navigation bar-->
<header>
    <nav>
        <ul>
            <li class="img"><img src="{% static 'images/note.png' %}"/></li>
            <li><a href="{% url 'index' %}">Notes</a></li>
            <li class="right">
                <a href="{% url 'add note' %}">Add Note</a>
                <a href="{% url 'profile' %}">Profile</a>
            </li>
        </ul>
    </nav>
</header>
<!--end navigation bar-->


    <h1>My Notes</h1>


{#    <h2>There are no notes.</h2>#}
    <!--notes container-->
    {% if notes %}
    <div class="note-container">
        {% for note in notes %}
        <h2>{{ note.title}} <img src="{{ note.image_URL}}"/></h2>


        <div class="right">
            <a class="button details" href="{% url 'details note' pk=note.pk %}">Details</a>
            <a class="button edit" href="{% url 'edit note' pk=note.pk %}">Edit</a>
            <a class="button delete" href="{% url 'delete note' pk=note.pk %}">Delete</a>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <h2>There are no notes.</h2>
    {% endif %}

{#    <div class="note-container">#}
{#        <h2>Python Web Basics <img src="https://about.softuni.bg/Content/images/home-page/softuni-logo.svg"/></h2>#}
{##}
{#        <div class="right">#}
{#            <a class="button details" href="/details/4">Details</a>#}
{#            <a class="button edit" href="/edit/4">Edit</a>#}
{#            <a class="button delete" href="/delete/4">Delete</a>#}
{#        </div>#}
{#    </div>#}


<!--end notes container-->

<footer>
    <div>Python Web Basics Exam @SoftUni</div>
</footer>
</body>
</html>

Python Web/epfour/templates/note-create.html
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" type="text/css" href="/static/css/style.css" />
        <title>Notes</title>
    </head>

    <body>
        <!--navigation bar-->
        <header>
            <nav>
                <ul>
                    <li class="img"><img src="{% static 'images/note.png' %}" /></li>
                    <li><a href="{% url 'index' %}">Notes</a></li>
                    <li class="right"><a href="{% url 'profile' %}">Profile</a></li>
                </ul>
            </nav>
        </header>
        <!--end navigation bar-->

        <div class="body">
            <!--headings-->
            <h1>Add Note</h1>
            <!--headings-->

            <!--note data form-->
            <div class="form">
                <form method="post" action="{% url 'add note' %}">
                    {{ form }}
{#                    <input type="hidden" name="csrfmiddlewaretoken" value="HUrRfZ1Xv8I1kg0RCRhg5I8sTJMRfcaLEI9Pf4LGjQXUjsQgoxLnWAleb0K01njw" />#}
{#                    <label for="name">Title</label>#}
{#                    <input type="text" name="title" maxlength="50" required="" id="id_title" />#}
{##}
{#                    <label for="content">Content</label>#}
{#                    <textarea name="description" cols="40" rows="10" required="" id="id_description"></textarea>#}
{##}
{#                    <label for="image_url">Link to Image</label>#}
{#                    <input type="url" name="image_url" maxlength="200" required="" id="id_image_url" />#}

                    <input type="submit" value="Publish" />
                    {% csrf_token %}
                </form>
            </div>
            <!--end note data form-->
        </div>

        <!--footer-->
        <footer>
            <div>Python Web Basics Exam @SoftUni</div>
        </footer>
        <!--end footer-->
    </body>
</html>

Python Web/epfour/templates/note-delete.html
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
        <title>Notes</title>
    </head>

    <body>
        <!--navigation bar-->
        <header>
            <nav>
                <ul>
                    <li class="img"><img src="{% static 'images/note.png' %}" /></li>
                    <li><a href="{% url 'index' %}">Notes</a></li>
                    <li class="right">
                        <a href="{% url 'add note' %}">Add Note</a>
                        <a href="{% url 'profile' %}">Profile</a>
                    </li>
                </ul>
            </nav>
        </header>
        <!--navigation bar-->

        <div class="body">
            <!--headings-->
            <h1>Delete Note</h1>
            <!--headings-->

            <!--note delete data form-->
            <div class="form">
                <form method="post" action="{% url 'delete note' pk=note.pk%}">
                    {{ form }}
{#                    <input type="hidden" name="csrfmiddlewaretoken" value="hwapnt8nZjnQuJ2M6SZBuXGgOwc3fZlrekSnnyS6N1CJtVSbSytIlPT26Nac1auc" />#}
{#                    <label for="name">Title</label>#}
{#                    <input type="text" name="title" value="Today's Tasks" maxlength="50" disabled="" required="" id="id_title" />#}
{##}
{#                    <label for="content">Content</label>#}
{#                    <textarea name="description" cols="40" rows="10" disabled="" required="" id="id_description">#}
{#Today I need to go shopping, make some pancakes, and at the end of the day I should write some code.#}

{#                    </textarea>#}

{#                    <label for="image_url">Link to Image</label>#}
{#                    <input type="url" name="image_url" value="https://www.freeiconspng.com/thumbs/tasks-icon/tasks-icon-9.png" maxlength="200" disabled="" required="" id="id_image_url" />#}

                    <input type="submit" value="Delete" />
                    {% csrf_token %}
                </form>
            </div>
            <!--end note delete data form-->
        </div>

        <!--footer-->
        <footer>
            <div>Python Web Basics Exam @SoftUni</div>
        </footer>
        <!--end footer-->
    </body>
</html>

Python Web/epfour/templates/note-details.html
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
        <title>Notes</title>
    </head>

    <body>
        <!--navigation bar-->
        <header>
            <nav>
                <ul>
                    <li class="img"><img src="{% static 'images/note.png' %}" /></li>
                    <li><a href="{% url 'index' %}">Notes</a></li>
                    <li class="right">
                        <a href="{% url 'add note' %}">Add Note</a>
                        <a href="{% url 'profile' %}">Profile</a>
                    </li>
                </ul>
            </nav>
        </header>
        <!--end navigation bar-->

        <div class="body">
            <!--headings-->
            <h1>Note Details</h1>
            <!--headings-->

            <!--details note box-->
            <div class="note-details-container">
                <h2>{{ note.title}}</h2>
                <img class="detail-img" src="{{ note.image_URL}}" alt="note-image" />
                <div>
                    <p>Content</p>
                </div>
                <p>
                    {{ note.content}}
                </p>
                <div class="right">
                    <a class="button edit" href="{% url 'edit note' pk=note.pk %}">Edit</a>
                    <a class="button delete" href="{% url 'delete note' pk=note.pk %}">Delete</a>
                </div>
            </div>
            <!--end details note box-->
        </div>

        <!--footer-->
        <footer>
            <div>Python Web Basics Exam @SoftUni</div>
        </footer>
        <!--end footer-->
    </body>
</html>

Python Web/epfour/templates/note-edit.html
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css'%}" />
        <title>Notes</title>
    </head>

    <body>
        <!--navigation bar-->
        <header>
            <nav>
                <ul>
                    <li class="img"><img src="{% static 'images/note.png' %}" /></li>
                    <li><a href="{% url 'index' %}">Notes</a></li>
                    <li class="right">
                        <a href="{% url 'add note' %}">Add Note</a>
                        <a href="{% url 'profile' %}">Profile</a>
                    </li>
                </ul>
            </nav>
        </header>
        <!--end navigation bar-->

        <div class="body">
            <!--headings-->
            <h1>Edit Note</h1>
            <!--headings-->

            <!--note edit data form-->
            <div class="form">
                <form method="post" action={% url 'edit note' pk=note.pk%}>
                    {{ form }}
{#                    <input type="hidden" name="csrfmiddlewaretoken" value="E8qoLvlyiXBfE7NlcyWlXe1TMWV5qvo7BW8mLA5h6FQ8DjDKYeqsO6eF4dTecGxS" />#}
{#                    <label for="name">Title</label>#}
{#                    <input type="text" name="title" value="Today's Tasks" maxlength="50" required="" id="id_title" />#}
{##}
{#                    <label for="content">Content</label>#}
{#                    <textarea name="description" cols="40" rows="10" required="" id="id_description">Today I need to go shopping, make some pancakes, and at the end of the day I should write some code.</textarea>#}
{##}
{#                    <label for="image_url">Link to Image</label>#}
{#                    <input type="url" name="image_url" value="https://www.freeiconspng.com/thumbs/tasks-icon/tasks-icon-9.png" maxlength="200" required="" id="id_image_url" />#}

                    <input type="submit" value="Edit" />
                    {% csrf_token %}
                </form>
            </div>
            <!--end note edit data form-->
        </div>

        <!--footer-->
        <footer>
            <div>Python Web Basics Exam @SoftUni</div>
        </footer>
        <!--end footer-->
    </body>
</html>

Python Web/epfour/templates/profile.html
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
        <title>Notes</title>
    </head>

    <body>
        <!--navigation bar-->
        <header>
            <nav>
                <ul>
                    <li class="img"><img src="{% static 'images/note.png' %}" /></li>
                    <li><a href="{% url 'index' %}">Notes</a></li>
                    <li class="right">
                        <a href="{% url 'add note' %}">Add Note</a>
                        <a href="{% url 'profile' %}">Profile</a>
                    </li>
                </ul>
            </nav>
        </header>
        <!--end navigation bar-->

        <div class="body">
            <!--headings-->
            <h1>Your Profile</h1>
            <!--end headings-->

            <!--profile details container TODO-->
            <div class="note-container">
                <h2>
                    {{ profile.first_name}} {{ profile.last_name }}
                    <img src="{{ profile.image_URL}}" />
                </h2>
                <p>Age: {{ profile.age }}</p>
                <div>
                    <p>All notes: {{ notes }}</p>
                </div>
                <div class="right">
                    <a class="button delete" href="{% url 'index' %}">Delete</a>
                </div>
            </div>
            <!--end profile details container-->
        </div>

        <!--footer-->
        <footer>
            <div>Python Web Basics Exam @SoftUni</div>
        </footer>
        <!--end footer-->
    </body>
</html>